const services = [
    {name:"National Emergency", number:"112", category:"police"},
    {name:"Police", number:"100", category:"police"},
    {name:"Fire Service", number:"101", category:"fire"},
    {name:"Ambulance", number:"108", category:"medical"},
    {name:"Government Ambulance", number:"102", category:"medical"},
    {name:"Blood Bank Helpline", number:"104", category:"medical"},
    {name:"Women Helpline", number:"181", category:"women"},
    {name:"Women Domestic Violence", number:"1091", category:"women"},
    {name:"Child Helpline", number:"1098", category:"child"},
    {name:"Cyber Crime Helpline", number:"1930", category:"cyber"},
    {name:"Senior Citizen Helpline", number:"14567", category:"senior"},
    {name:"Railway Protection Force", number:"182", category:"police"},
    {name:"Disaster Management", number:"1078", category:"disaster"},
    {name:"Road Accident Emergency", number:"1073", category:"road"},
    {name:"Gas Leakage Emergency", number:"1906", category:"gas"},
    {name:"Tourist Helpline", number:"1363", category:"security"},
    {name:"Tourist Helpline Toll Free", number:"1800111363", category:"security"},
    {name:"Election Commission Helpline", number:"1950", category:"security"},
    {name:"Electricity Emergency Complaint", number:"1912", category:"security"},
    {name:"Water Supply Emergency", number:"1916", category:"security"},
    {name:"Farmer Call Centre", number:"1551", category:"security"},
    {name:"Consumer Helpline", number:"1800114000", category:"security"},
    {name:"Anti Ragging Helpline", number:"18001805522", category:"security"},
    {name:"Mental Health Helpline", number:"9152987821", category:"medical"},
    {name:"Anti Poison", number:"1066", category:"medical"},
    {name:"AIDS Helpline", number:"1097", category:"medical"},
    {name:"Railway Enquiry", number:"139", category:"transport"},
    {name:"LPG Emergency Helpline", number:"155233", category:"gas"},
    {name:"Missing Child Helpline", number:"1094", category:"child"}
];